# CHURN MODEL

import pandas as pd

In [2]:
import numpy as np

In [3]:
churn_mol=pd.read_csv('Churn_Modelling.csv')

In [4]:
churn_mol.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
churn_mod = churn_mol.drop(columns=["RowNumber","CustomerId","Surname"], axis = 1)

In [6]:
churn_mod.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
churn_mol.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
# if there is no 0 answer then -----  df['coulmn name'].fillna(df['same column'].mean(),inplace=True)

In [9]:
churn_mol["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
churn_mol.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [11]:
churn_mod = pd.get_dummies(churn_mod, dtype=float)

In [12]:
churn_mod.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0,1.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0,1.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0,1.0,0.0

In [13]:
# churn_mol['Gender_Male'] = churn_mol['Gender_Male'].astype(int)

# print(churn_mol)
# churn_mol['Gender_Male'] = churn_mol['Gender_Male'].replace({True: 1, False: 0})

# print(churn_mol)

boolean_cols = churn_mol.select_dtypes(include=['bool']).columns
churn_mol[boolean_cols] = churn_mol[boolean_cols].astype(int)

In [14]:
boolean_cols

Index([], dtype='object')

In [15]:
churn_mod.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_France',
       'Geography_Germany', 'Geography_Spain', 'Gender_Female', 'Gender_Male'],
      dtype='object')

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
  # Replace with your actual target column name
# IsActiveMember


X= churn_mod.drop(columns='IsActiveMember',axis=1)
y = churn_mod['IsActiveMember']

In [18]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,101348.88,1,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,112542.58,0,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,113931.57,1,1.0,0.0,0.0,1.0,0.0
3,699,39,1,0.00,2,0,93826.63,0,1.0,0.0,0.0,1.0,0.0
4,850,43,2,125510.82,1,1,79084.10,0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,96270.64,0,1.0,0.0,0.0,0.0,1.0
9996,516,35,10,57369.61,1,1,101699.77,0,1.0,0.0,0.0,0.0,1.0
9997,709,36,7,0.00,1,0,42085.58,1,1.0,0.0,0.0,1.0,0.0
9998,772,42,3,75075.31,2,1,92888.52,1,0.0,1.0,0.0,0.0,1.0
9999,792,28,4,130142.79,1,1,38190.78,0,1.0,0.0,0.0,1.0,0.0

In [19]:
y

0       1
1       1
2       0
3       0
4       1
       ..
9995    0
9996    1
9997    1
9998    0
9999    0
Name: IsActiveMember, Length: 10000, dtype: int64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y)

In [21]:
churn_mod.shape

(10000, 14)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
model = LogisticRegression()

In [24]:
model.fit(X_train,y_train)

/home/sumit/miniconda3/envs/ml/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [25]:
prediction = model.predict(X_test)

In [26]:
prediction

array([0, 1, 1, ..., 1, 1, 0])

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [28]:
accuracy = accuracy_score(y_test, prediction)
print(f'Accuracy: {accuracy:.2f}')




# Precision
precision = precision_score(y_test,prediction)
print(f'Precision: {precision:.2f}')

# Recall
recall = recall_score(y_test, prediction)
print(f'Recall: {recall:.2f}')

# # F1 Score
f1 = f1_score(y_test, prediction)
print(f'F1 Score: {f1:.2f}')

# # Confusion Matrix
conf_matrix = confusion_matrix(y_test, prediction)
print('Confusion Matrix:')
print(conf_matrix)

# # Classification Report
class_report = classification_report(y_test,prediction)
print('Classification Report:')
print(class_report)

Accuracy: 0.54
Precision: 0.54
Recall: 0.69
F1 Score: 0.61
Confusion Matrix:
[[372 598]
 [315 715]]
Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.38      0.45       970
           1       0.54      0.69      0.61      1030

    accuracy                           0.54      2000
   macro avg       0.54      0.54      0.53      2000
weighted avg       0.54      0.54      0.53      2000